#!/usr/bin/python

import argparse
import csv

parser = argparse.ArgumentParser(description='Process Sparkasse Koeln-Bonn CSV File')
parser.add_argument('file', metavar='files', type=str, nargs=1, help='csv file')

arguments = parser.parse_args()

with open(arguments.file[0], 'rU') as input:
    with open('quicken.csv', 'w') as output:
        reader = csv.reader(input, delimiter=';', quotechar='"')

        fieldnames = ['Date', 'Description', 'Amount']
        writer = csv.DictWriter(output, fieldnames=fieldnames, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
        writer.writeheader()

        for row in reader:
            valuta = row[2]
            info = row[16].replace(r'^M', '')

            if info == 'Umsatz vorgemerkt' or valuta == 'Valutadatum':
                continue

            d = valuta.split('.')

            buchungstext = row[3]
            verwendungszweck = row[4]
            beguenstigter = row[11]
            description = "%s | %s | %s" % (buchungstext, verwendungszweck, beguenstigter)

            betrag = row[14].replace(',','')

            writer.writerow({'Date': "%s.%s.20%s" % (d[0],d[1],d[2]), 'Description': description, 'Amount': betrag})
